version: '3'
services:
  react-app:
    # build: 
    #   context: ./client/
    #   dockerfile: Dockerfile
    # container_name: react-frontend
    image: react-app-dev
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - .
    stdin_open: true

  backend-api:
    # build:
    #   context: ./server/
    #   dockerfile: Dockerfile
    # container_name: express-backend
    image: api-server
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app
    depends_on:
      - mongo

  mongo:
    image: mongo:4.4-bionic
    container_name: mongo_DB
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
    driver: local